### ISSUE TITLE
Can it skip Proxy/Abstract model?

### ISSUE THREAD

**Issue by xjlin0** [vanadium23/django-db-comments#11]
* Django Db Comments version: 0.3.1
* Django version: 3.2.11
* Python version: 3.9.10, with django-pghistory 1.2.1
* Operating System: MacOS 11.5.2 with docker images on Debian bullseye

### Description

When migration, it failed showing database table is missing, however, it's a proxy model, it should not have any tables.  Could django-db-comments skip proxy/abstract models?
```
class Meta:
    managed = False
    # or
    abstract = True
    # or
    proxy = True
```

### What I Did

```
$ docker-compose -f local.yml run django python manage.py migrate
Starting redis   ... done
Starting mailhog ... done
Starting postgres ... done
PostgreSQL is available

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/pgconnection/core.py", line 85, in execute
    return super().execute(sql, args)
psycopg2.errors.UndefinedTable: relation "pghistory_aggregateevent" does not exist
```

**Comment by vanadium23** [comment]
Release v0.4.0 with your request.
